name: "Release - Drafter"
on:
  issues:
    types: [ closed,reopened ]
  push:
    branches:
      - '[0-9]+.[0-9]+.x'
      - 'main'
  pull_request:
    types: [ opened, reopened, synchronize, labeled ]
  workflow_dispatch:
# queue jobs and only allow 1 run per branch due to the likelihood of hitting GitHub resource limits
concurrency:
  group: release-pipeline
  cancel-in-progress: false
jobs:
  update_release_draft:
    permissions:
      contents: write # write permission is required to create a github release
      pull-requests: write # write permission is required for auto-labeler
    runs-on: ubuntu-latest
    steps:
      - name: "üìù Update Release Draft"
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
